---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgByi5mCgb6Dop+49ev/NhJ8aTttTQR3c3Vl/8RotIQ+TDh9sYq/CWWPJ5r+B6KHgYJAgaHZI7Qy3R9AD9M2AJv+FYDwVJuBsnh+cjN9W0g0IVVIxfKUnihanwge+pOGZucYDBcfiNrg1/xenyKumfjitMiaVBxMBq75Poba7FpE6kwnPLryDCYAUKq1o3NmU2HlFEYrRdo1EAVsVeuJkFkGBSYigUW26lU5I+z0Ld6TaOUzmDD5snp3xxIN+0ytQCICeMeRznuf2Ovpa/IGzRdJadBEmLb5exJlV6RPOAEZvLa88qvcNGhNdi/ORbipByEvAyDc85cxVNua+d2L9aPRXxY/Fh2NV9cp7Awz1Ws/WWiIteydvZQ4EYsxINCFYkIgIzTHSkFMV91Ng/4ROS6h2mFs3v6b2K7f0xcCrQhLlWMyVqagC6kicUmndiWa7rPnpPeLbtF3kb+c0T1PRAPBIT4C1nEwOdQYKP3RLReilePevJQngShpVMAOxJ1jyqQb8bHmpm+pKLv0+GmZ5dAlSWhJrAB8pgaxWmRtCJidOI2V8sSkoTLdtpm1ZGHQS0BxRTbBbw7Cw5ybJLNso6fWE2tJXXL8wAFHVXvU/22POxs+1Yj/uxqF5KTAprKdwgOCj84lchg6cLkfZ8LUjKTX0pxiPXtN9QVw5x2jJu0K1E+0rp+eR1F7WPuhCx7+d9W1slMAIqXLAh+5YHhWsk8C7Y9rz4IJhQ6+8L5SGAQ2SUR0INjzE+gFpHTCrhCeM6PynJguV7717u3toiY/Z6jaynVOhf9/fbu1X1L4CiV5SFFIvk76covEWGR2n+1ceewZRKyrJQyI81iaph5werh2RT8jKub9
  template:
    metadata:
      name: vaultwarden-admin
      namespace: vaultwarden
    type: Opaque
