apiVersion: v2
name: longhorn
description: Deploy Longhorn distributed storage
type: application
version: 0.1.0

dependencies:
  - name: longhorn
    version: 1.12.1
    repository: https://charts.longhorn.io
