coredns:
  isClusterService: false

  replicaCount: 1

  serviceType: LoadBalancer
  
  service:
    # Optional: request a specific IP from your Cilium pool instead of the next free one
    annotations:
      io.cilium/lb-ipam-ips: "192.168.178.222"

  servers:
    - zones:
        - zone: .
      port: 53
      plugins:
        - name: errors
        - name: health
        - name: ready
        - name: hosts
          parameters: homelab.hosts
          configBlock: |
            192.168.178.221 argocd.homelab
            fallthrough
        - name: forward
          parameters: . 1.1.1.1 1.0.0.1
        - name: cache
          parameters: 30
        - name: loop
        - name: reload
        - name: loadbalance

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi