gateway-helm:
  service:
    type: ClusterIP

routes:
  - name: argocd
    staticIP: "192.168.178.221"
    backendNamespace: argocd
    backendServiceName: argocd-server
    backendServicePort: 80
  - name: longhorn
    staticIP: "192.168.178.222"
    backendNamespace: longhorn-system
    backendServiceName: longhorn-frontend
    backendServicePort: 80
  - name: adguard-home
    staticIP: "192.168.178.223"
    backendNamespace: adguard-home
    backendServiceName: adguard-home-web
    backendServicePort: 80
  - name: jellyfin
    staticIP: "192.168.178.225"
    backendNamespace: media
    backendServiceName: jellyfin
    backendServicePort: 8096
  - name: sabnzbd
    staticIP: "192.168.178.226"
    backendNamespace: media
    backendServiceName: sabnzbd
    backendServicePort: 8080
  - name: sonarr
    staticIP: "192.168.178.227"
    backendNamespace: media
    backendServiceName: sonarr
    backendServicePort: 8989
  - name: radarr
    staticIP: "192.168.178.228"
    backendNamespace: media
    backendServiceName: radarr
    backendServicePort: 7878
  - name: prowlarr
    staticIP: "192.168.178.229"
    backendNamespace: media
    backendServiceName: prowlarr
    backendServicePort: 9696
  - name: bazarr
    staticIP: "192.168.178.230"
    backendNamespace: media
    backendServiceName: bazarr
    backendServicePort: 6767
  - name: seerr
    staticIP: "192.168.178.231"
    backendNamespace: media
    backendServiceName: seerr
    backendServicePort: 5055

