jellyfin:
  persistence:
    config:
      size: "5Gi"
    media:
      existingClaim: media-server-data

  service:
    type: ClusterIP 

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
