apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  labels:
    category: infra
spec:
  project: default
  source:
    repoURL: https://github.com/Y3llowm4n/Mike_HomeLab
    targetRevision: main
    path: charts/infrastructure/coredns/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true